NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GC5ZMSJN3E6IW5VOT55PEPLCTJFT7NQBLKKTGYFG4ZDUHLQ7M7BKNNLC",
"GCVH3ZH4JQHI5SWNFAHM6LYVBTYWDB5B54WKEUQZI6LCKTRLB2RSLZJ4"
]

[DOCUMENTATION]
ORG_NAME="ARBT"
ORG_URL="https://arbto.github.io"
ORG_LOGO="https://arbto.github.io/logo.png"
ORG_DESCRIPTION="ARBT is a meme-inspired cryptocurrency that has learnt a few tricks from the memes father dogecoin and aims to sustain a more profitable cryptoverse for everyone. $ARBT tokens will be in existence for as long as Stellar blockchain network exist."
ORG_PHYSICAL_ADDRESS="Milan, Italy"
ORG_KEYBASE="acoshirabbit"
ORG_TWITTER="AcoshiRabbit"
ORG_OFFICIAL_EMAIL="yvettealfred5@gmail.com"

[[CURRENCIES]]
code="ARBT"
issuer="GBJUUYLCALIBUOLEWDJKAWCWVWQ7AV3T2FBFVVNB3KRJIZ3U2RFSCDLR"
display_decimals=7
name="Acoshi Rabbit"
desc="Acoshi Rabbit (ARBT) is a meme-inspired cryptocurrency that has learnt a few tricks from the memes father dogecoin and aims to sustain a more profitable cryptoverse for everyone."
is_asset_anchored=false
conditions="There will only ever be 100,000,000,000 $ARBT tokens in existence on the Stellar blockchain network. Join the moon mission and keep spreading the news!."
image="https://arbto.github.io/logo.png"
fixed_number=100000000000
status="live"
